name: Auto-merge

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    # Auto-merge pour :
    # 1) PR Release Please (branche release-please--branches--*)
    # 2) PR humaines si label "automerge" est prÃ©sent
    if: >
      startsWith(github.head_ref, 'release-please--branches--') ||
      contains(join(github.event.pull_request.labels.*.name, ','), 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (squash)
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MERGE_METHOD: squash
