name: Auto-merge

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    # Merge uniquement si (release-please branch) OU (label automerge présent)
    if: ${{ startsWith(github.head_ref, 'release-please--branches--') || contains(join(github.event.pull_request.labels.*.name, ','), 'automerge') }}
    runs-on: ubuntu-latest

    steps:
      - name: Auto-merge (squash) when checks are green
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MERGE_METHOD: squash
          # optionnel mais recommandé :
          UPDATE_METHOD: rebase
          MERGE_DELETE_BRANCH: "true"
