name: Auto-merge

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    # Auto-merge uniquement pour PR des bots (release)
    if: >
      github.event.pull_request.user.login == 'github-actions[bot]' ||
      github.event.pull_request.user.login == 'release-please[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (squash)
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MERGE_METHOD: squash
